import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { UserProvider } from "@/utils/contexts";
import LogInWrapper from "@/components/LogInWrapper";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <UserProvider>
          <Header/>
          <LogInWrapper children={children}/>
        </UserProvider>
        
      </body>
    </html>
  );
}
